name: CI

on:
  push: 
    branches: [ $default-branch ]
  pull_request: 
    branches: [ $default-branch ]

jobs:
  industrial_ci:
    name: "Industrial CI"
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
